### ISSUE TITLE
Delete button z-index issues

### ISSUE THREAD

**Issue by flipcard-io** [editor-js/table#179]
It appears that when I have some paragraphs below the table and I try to delete the row, it is impossible due to the fact the delete button appears what seems to be the paragraph content. Attached an image for visibility.

Version: 2.4.4

<img width="458" alt="Image" src="https://github.com/user-attachments/assets/c16ae114-895e-4cc9-aafc-434c75a4c24f" />

**Comment by nvsang2000** [comment]
There is no solution to this problem.

**Comment by nvsang2000** [comment]
@flipcard-io @adrienne @JoeWoodward @hortopan I am also having this error, is there any way to fix it before the team updates?

**Comment by jonathangjertsen** [comment]
You can work around the issue by nudging the popover upwards a little bit with CSS. 

```css
.tc-toolbox .tc-popover {
  top: -2em !important;
}
```

**Comment by PhanhotboY** [comment]
The alternative solution is setting `z-index` of `ce-block__content` to 1 when the popover is showing up
```css
.ce-block__content:has(.tc-popover.tc-popover--opened) {
    z-index: 1;
}
```
I think the problem is the popover is absolute to `ce-block__content` and `ce-block__content` has lower `z-index` to the next one, therefore setting `ce-block__content`'s `z-index` solves the problem here.
